# Netlify configuration file
[build]
  publish = "dist"
  command = "npm run build"

[dev]
  command = "npm start"
  port = 3000

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
